from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / os.getenv("DATA_DIR", "data")
UPLOADS_DIR = DATA_DIR / "uploads"
ARTIFACTS_DIR = DATA_DIR / "artifacts"

UPLOADS_DIR.mkdir(parents=True, exist_ok=True)
ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)

PREFECT_API_URL = os.getenv("PREFECT_API_URL", "http://127.0.0.1:4200/api")

ARCHITECTURES = {
    "kernarc":  "Kuantan Arc",
    "swiftpan": "SwiftPan",
    "sepfuse":  "SepFuse",
    "dualfuse": "DualFuse",
    "syncgen":  "SyncGen",
    "nanonet":  "NanoNet",
    "alexnet": "AlexNet",
    "vggnet": "VGGNet",
    "resnet": "ResNet",
    "inceptionv3": "Inception v3",
    "efficientnet": "EfficientNet",
    "vit": "Vision Transformer (ViT)",
    "densenet": "DenseNet",
    "mobilenet": "MobileNet",
    "swin": "Swin Transformer",
    "convnext": "ConvNeXt",
}

ARCHITECTURE_CATALOG = {
    "kernarc": {
        "badge": "Custom",
        "intro": "Multi-kernel attention CNN that fuses short-, mid-, and wide-receptive-field convolutions into a sigmoid gate over the image.",
        "why": "Useful when local detail and broader context both matter in a lightweight custom backbone.",
        "layers": [
            "Input RGB image",
            "Rescaling(1/255)",
            "Parallel Conv2D branches: 2x2, 4x4, 8x8",
            "Concatenate -> BatchNorm -> Conv2D(3x3) -> BatchNorm",
            "MaxPooling2D(4)",
            "Conv2D sigmoid attention gate",
            "Resize original input and Multiply with gate",
            "Conv2D(64) -> MaxPool -> Conv2D(128)",
            "GlobalAveragePooling2D -> Dense(256) -> Dropout -> Softmax",
        ],
    },
    "swiftpan": {
        "badge": "Custom",
        "intro": "A narrow three-stage attention chain that repeatedly mixes a small-kernel branch with a large-kernel context branch.",
        "why": "Designed for quick experiments and low-memory runs where a tiny preprocessing stem is desirable.",
        "layers": [
            "Input RGB image",
            "Rescaling(1/255)",
            "1x1 projection to single-channel attention map",
            "Stage 1: Conv3x3 * reference + Conv9x9 -> MaxPool",
            "Stage 2: Conv3x3 * pooled reference + Conv9x9 -> MaxPool",
            "Stage 3: Conv3x3 * pooled reference + Conv9x9 -> MaxPool",
            "BatchNorm -> Conv2D(3 channels) -> BatchNorm",
            "Conv2D(64) -> Conv2D(128)",
            "GlobalAveragePooling2D -> Dense(256) -> Dropout -> Softmax",
        ],
    },
    "sepfuse": {
        "badge": "Custom",
        "intro": "A separable-convolution encoder with a compact top-down feature pyramid merge path.",
        "why": "Useful for multi-scale texture recognition and datasets where feature reuse across scales matters.",
        "layers": [
            "Input RGB image",
            "Rescaling(1/255)",
            "Bottom-up blocks: SeparableConv2D -> BatchNorm -> ReLU -> MaxPool",
            "Feature levels c1, c2, c3, c4",
            "Lateral 1x1 separable projections",
            "Top-down UpSampling2D + Add pyramid fusion",
            "BatchNorm on merged pyramid maps",
            "GlobalMaxPooling2D",
            "Dense(256) -> Dropout -> Dense(128) -> Dropout -> Softmax",
        ],
    },
    "dualfuse": {
        "badge": "Custom",
        "intro": "A dual-stream CNN that sees the same image at full and half resolution before feature fusion.",
        "why": "Useful when the same class can appear at noticeably different apparent scales.",
        "layers": [
            "Input RGB image",
            "Rescaling(1/255)",
            "Stream A: Conv7x7 -> MaxPool -> Conv5x5 -> MaxPool -> Conv3x3 -> MaxPool",
            "GlobalAveragePooling2D on Stream A",
            "Resize input to half resolution",
            "Stream B: Conv5x5 -> MaxPool -> Conv3x3 -> MaxPool",
            "GlobalAveragePooling2D on Stream B",
            "Concatenate stream vectors",
            "Dense(512) -> Dropout -> Dense(256) -> Dropout -> Softmax",
        ],
    },
    "syncgen": {
        "badge": "Custom",
        "intro": "A strided encoder built as the reverse of a generator-like decoder, using progressive compression blocks.",
        "why": "Fits structured or synthetic-looking image domains where strong staged downsampling is acceptable.",
        "layers": [
            "Input RGB image",
            "Rescaling(1/255)",
            "Conv2D(5x5, stride 2) -> BatchNorm -> LeakyReLU",
            "Conv2D(5x5, stride 2) -> BatchNorm -> LeakyReLU",
            "Conv2D(5x5, stride 4) -> BatchNorm -> LeakyReLU",
            "Conv2D(5x5, stride 2) -> BatchNorm -> LeakyReLU",
            "GlobalAveragePooling2D",
            "Dense(256) -> BatchNorm -> LeakyReLU -> Dropout",
            "Softmax classifier",
        ],
    },
    "nanonet": {
        "badge": "Custom",
        "intro": "A small MobileNet-style classifier using separable convolutions and ReLU6 activations.",
        "why": "Good when training speed and memory footprint matter more than raw backbone capacity.",
        "layers": [
            "Input RGB image",
            "Rescaling(1/255)",
            "Stem Conv2D(stride 2) -> BatchNorm -> ReLU6",
            "Depthwise-separable blocks with channel progression 32 -> 64 -> 128 -> 256",
            "Stride-2 blocks handle spatial downsampling",
            "GlobalAveragePooling2D",
            "Dense(256) -> Dropout -> Softmax",
        ],
    },
    "alexnet": {
        "badge": "Classic",
        "intro": "The architecture that kicked off the modern deep learning era in computer vision with wide early convolutions and a large classifier head.",
        "why": "Important as a historical baseline and still useful for illustrating early CNN design choices.",
        "layers": [
            "Input RGB image",
            "Rescaling(1/255)",
            "Conv2D(11x11, stride 4) -> MaxPool",
            "Conv2D(5x5) -> MaxPool",
            "Conv2D(3x3) -> Conv2D(3x3) -> Conv2D(3x3)",
            "MaxPool",
            "GlobalAveragePooling2D",
            "Dense(512) -> Dropout -> Dense(512) -> Dropout -> Softmax",
        ],
    },
    "vggnet": {
        "badge": "Classic",
        "intro": "A deep plain CNN built from repeated 3x3 convolutions and max-pooling blocks.",
        "why": "Showed that depth plus simple repeated building blocks can outperform more handcrafted designs.",
        "layers": [
            "Input RGB image",
            "Rescaling(1/255)",
            "Block 1: Conv3x3 x2 -> MaxPool",
            "Block 2: Conv3x3 x2 -> MaxPool",
            "Block 3: Conv3x3 x3 -> MaxPool",
            "Block 4: Conv3x3 x3 -> MaxPool",
            "Block 5: Conv3x3 x3 -> MaxPool",
            "GlobalAveragePooling2D",
            "Dense(512) -> Dropout -> Softmax",
        ],
    },
    "resnet": {
        "badge": "Recommended",
        "intro": "Residual networks add skip connections so deeper CNNs train stably instead of degrading.",
        "why": "Still the most reliable general-purpose backbone family for image tasks and the default choice here.",
        "layers": [
            "Input RGB image",
            "Rescaling(1/255)",
            "Stem Conv2D(7x7, stride 2) -> BatchNorm -> ReLU -> MaxPool",
            "Residual stage 64 channels",
            "Residual stage 128 channels with downsampling",
            "Residual stage 256 channels with downsampling",
            "Residual stage 512 channels with downsampling",
            "GlobalAveragePooling2D",
            "Dense(256) -> Dropout -> Softmax",
        ],
    },
    "inceptionv3": {
        "badge": "Classic",
        "intro": "An architecture that mixes multiple convolution scales in parallel within each module.",
        "why": "Useful when width and multi-scale processing matter as much as simply stacking depth.",
        "layers": [
            "Input RGB image",
            "Rescaling(1/255)",
            "Conv stem with stride-2 reduction",
            "MaxPool -> 1x1 and 3x3 projection layers",
            "Inception module: parallel 1x1, 3x3, 5x5, pooled branch",
            "Repeated Inception modules with intermediate downsampling",
            "GlobalAveragePooling2D",
            "Dense(320) -> Dropout -> Softmax",
        ],
    },
    "efficientnet": {
        "badge": "Efficient",
        "intro": "A compact MBConv-based network with squeeze-excitation and balanced scaling ideas.",
        "why": "For years it set the standard for strong accuracy relative to model size and compute cost.",
        "layers": [
            "Input RGB image",
            "Rescaling(1/255)",
            "Stem Conv2D(stride 2)",
            "MBConv stage with expand -> depthwise conv -> squeeze-excitation -> project",
            "Repeated MBConv stages with progressive width and downsampling",
            "1x1 Conv projection head",
            "GlobalAveragePooling2D",
            "Dense(320) -> Dropout -> Softmax",
        ],
    },
    "vit": {
        "badge": "Transformer",
        "intro": "A vision transformer that turns the image into fixed-size patches and processes them with self-attention.",
        "why": "It proved the transformer paradigm works on image classification and changed backbone design across vision.",
        "layers": [
            "Input RGB image",
            "Rescaling(1/255)",
            "Patch embedding via Conv2D with patch-size stride",
            "Flatten patches into token sequence",
            "Add learned positional embeddings",
            "Repeated transformer encoder blocks: LayerNorm -> MultiHeadAttention -> MLP",
            "LayerNormalization",
            "GlobalAveragePooling1D",
            "Dense -> Dropout -> Softmax",
        ],
    },
    "densenet": {
        "badge": "Medical",
        "intro": "A densely connected CNN where each block receives all earlier features as input.",
        "why": "Strong gradient flow and feature reuse make it especially popular on smaller and medical imaging datasets.",
        "layers": [
            "Input RGB image",
            "Rescaling(1/255)",
            "Stem Conv2D(7x7, stride 2) -> MaxPool",
            "Dense block with concatenative growth",
            "Transition block: BatchNorm -> 1x1 Conv -> AveragePool",
            "Repeated dense and transition stages",
            "Final BatchNorm -> ReLU",
            "GlobalAveragePooling2D",
            "Dense -> Dropout -> Softmax",
        ],
    },
    "mobilenet": {
        "badge": "Edge",
        "intro": "A mobile-first CNN built from depthwise separable convolutions and cheap pointwise projections.",
        "why": "It made deep vision practical on phones and edge hardware, and its building block is now standard.",
        "layers": [
            "Input RGB image",
            "Rescaling(1/255)",
            "Stem Conv2D(stride 2) -> BatchNorm -> ReLU6",
            "DepthwiseConv2D -> BatchNorm -> ReLU6",
            "Pointwise Conv2D -> BatchNorm -> ReLU6",
            "Repeated depthwise-separable stages with downsampling",
            "GlobalAveragePooling2D",
            "Dense(256) -> Dropout -> Softmax",
        ],
    },
    "swin": {
        "badge": "Transformer",
        "intro": "A hierarchical transformer that performs local self-attention in shifted windows over feature maps.",
        "why": "It made transformer backbones more practical for dense vision tasks by keeping attention local and multiscale.",
        "layers": [
            "Input RGB image",
            "Rescaling(1/255)",
            "Patch embedding Conv2D(stride 4)",
            "LayerNormalization",
            "Swin stage: window attention block",
            "Shifted-window attention block",
            "Patch merging / stride-2 Conv2D between stages",
            "Repeat hierarchical Swin stages with larger channel widths",
            "GlobalAveragePooling2D -> Dense -> Dropout -> Softmax",
        ],
    },
    "convnext": {
        "badge": "Modern CNN",
        "intro": "A ResNet-like CNN updated with large-kernel depthwise convolutions and transformer-inspired normalization and MLP ideas.",
        "why": "It showed that pure CNNs are still competitive when modernized with lessons learned from transformers.",
        "layers": [
            "Input RGB image",
            "Rescaling(1/255)",
            "Patchify stem Conv2D(stride 4)",
            "LayerNormalization",
            "ConvNeXt block: depthwise 7x7 conv -> LayerNorm -> MLP-style Dense expansion/projection",
            "Residual add with layer scaling",
            "Stride-2 Conv2D downsampling between stages",
            "Repeated ConvNeXt stages at higher widths",
            "GlobalAveragePooling2D -> Dense -> Dropout -> Softmax",
        ],
    },
}

ARCHITECTURE_KEYS = tuple(ARCHITECTURES.keys())
